---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# Introducing spatial availability, a singly-constrained competitive-access accessibility measure

Anastasia Soukhov (School of Earth, Environment and Society, McMaster University, Canada)
Antonio Paez (School of Earth, Environment and Society, McMaster University, Canada)
Christopher D. Higgins (Department of Geography & Planning, University of Toronto Scarborough, Canada)
Moataz Mohamed (Department of Civil Engineering, McMaster University, Canada)

Forthcoming in _Journal of Transport Geography_

<!-- badges: start -->
<!-- badges: end -->

# Abstract

Accessibility measures are widely used in transportation, urban and healthcare planning, among other applications. These measures are weighted sums of the opportunities that can be reached given the cost of movement and are interpreted to represent the potential for spatial interaction. Though these measures are useful in understanding spatial structure, their methodologies count available opportunities multiple times. This leads to interpretability issues, as noted in recent research on balanced floating catchment areas (BFCA) and competitive measures of accessibility. In this paper, we respond to the limitations of the accessibility measure by proposing a new measure of  _spatial availability_ which is calculated by imposing a single constraint on the conventional gravity-based accessibility. Similar to the gravity model from which spatial availability is derived, a single constraint ensures that the marginals at the destination are met and thus the number of opportunities are preserved. Through examples, we detail the formulation of the proposed measure. Further, we use data from the 2016 Transportation Tomorrow Survey of the Greater Golden Horseshoe area in southern Ontario, Canada, to contrast how the conventional accessibility measure tends to overestimate and underestimate the number of jobs _available_ to workers. We conclude with some discussion of the possible uses of spatial availability and argue that, compared to conventional measures of accessibility, it can offer a more meaningful and interpretable measure of opportunity access. All data and code used in this research are openly available.

# Keywords

- Spatial availability
- Accessibility
- Gravity model
- Transportation
- TTS

