\documentclass[]{elsarticle} %review=doublespace preprint=single 5p=2 column
%%% Begin My package additions %%%%%%%%%%%%%%%%%%%
\usepackage[hyphens]{url}

  \journal{Some Journal} % Sets Journal name


\usepackage{lineno} % add
  \linenumbers % turns line numbering on

\usepackage{graphicx}
%%%%%%%%%%%%%%%% end my additions to header

\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \usepackage{fontspec}
  \ifxetex
    \usepackage{xltxtra,xunicode}
  \fi
  \defaultfontfeatures{Mapping=tex-text,Scale=MatchLowercase}
  \newcommand{\euro}{€}
\fi
% use microtype if available
\IfFileExists{microtype.sty}{\usepackage{microtype}}{}
\bibliographystyle{elsarticle-harv}
\ifxetex
  \usepackage[setpagesize=false, % page size defined by xetex
              unicode=false, % unicode breaks when used with xetex
              xetex]{hyperref}
\else
  \usepackage[unicode=true]{hyperref}
\fi
\hypersetup{breaklinks=true,
            bookmarks=true,
            pdfauthor={},
            pdftitle={Introducing spatial availability, a singly-constrained competitive-access accessibility measure},
            colorlinks=false,
            urlcolor=blue,
            linkcolor=magenta,
            pdfborder={0 0 0}}
\urlstyle{same}  % don't use monospace font for urls

\setcounter{secnumdepth}{5}
% Pandoc toggle for numbering sections (defaults to be off)


% tightlist command for lists without linebreak
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}


% Pandoc citation processing
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newlength{\cslentryspacingunit} % times entry-spacing
\setlength{\cslentryspacingunit}{\parskip}
% for Pandoc 2.8 to 2.10.1
\newenvironment{cslreferences}%
  {}%
  {\par}
% For Pandoc 2.11+
\newenvironment{CSLReferences}[2] % #1 hanging-ident, #2 entry spacing
 {% don't indent paragraphs
  \setlength{\parindent}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
  \let\oldpar\par
  \def\par{\hangindent=\cslhangindent\oldpar}
  \fi
  % set entry spacing
  \setlength{\parskip}{#2\cslentryspacingunit}
 }%
 {}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{#1\hfill\break}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{#1}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{#1}\break}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\usepackage[font=small,skip=0pt]{caption}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{caption}
\usepackage{graphicx}
\usepackage{siunitx}
\usepackage{hhline}
\usepackage{calc}
\usepackage{tabularx}
\usepackage{adjustbox}
\usepackage{hyperref}



\begin{document}


\begin{frontmatter}

  \title{Introducing spatial availability, a singly-constrained
competitive-access accessibility measure}
      
  \begin{abstract}
  Accessibility measures are widely used in transportation, urban and
  healthcare planning, among other applications. These measures are
  weighted sums of the opportunities that can be reached given the cost
  of movement and are estimates of the potential for spatial
  interaction. These unconstrained measures are useful in understanding
  spatial structure, but they do not properly account for competition
  due to multiple counting of opportunities. This leads to
  interpretability issues, as noted in recent research on balanced
  floating catchment areas (BFCA) and competitive (doubly- or singly-
  constrained) measures of accessibility. In this paper, we respond to
  this limitation by proposing a new measure of \emph{spatial
  availability} which is calculated by imposing a single constraint on
  conventional gravity-based accessibility. This constraint ensures that
  the marginals at the destination are met and thus the number of
  opportunities are preserved across the analysis. Through examples, we
  detail the formulation of the proposed measure. Further, we use data
  from the 2016 Transportation Tomorrow Survey of the Greater Golden
  Horseshoe area in southern Ontario, Canada, to contrast how the
  conventional accessibility measure tends to overestimate and
  underestimate the number of jobs \emph{available} to workers. We
  conclude with some discussion of the possible uses of spatial
  availability and argue that, compared to conventional measures of
  accessibility, it can offer a more interpretable measure of
  opportunity access. All data and code used in this research are openly
  available which should facilitate testing by other researchers in
  their case studies.
  \end{abstract}
  
 \end{frontmatter}

\newpage

\hypertarget{introduction}{%
\section{Introduction}\label{introduction}}

Accessibility analysis is employed in transportation, geography, public
health, and many other areas, particularly as mobility-based planning is
de-emphasized in favor of access-oriented planning (Deboosere et al.,
2018; Handy, 2020; Proffitt et al., 2017; Yan, 2021). The concept of
accessibility derives its appeal from combining the spatial distribution
of opportunities and the cost of reaching them (Handy and Niemeier,
1997; Hansen, 1959).

Numerous methods for calculating accessibility have been proposed that
can be broadly organized into infrastructure-, place-, person-, and
utility-based measures (Geurs and van Wee, 2004). Of these, the
place-based family of measures is arguably the most common, capturing
the number of opportunities reachable from an origin using the
transportation network. One common type of accessibility measure is
based on the gravity model of spatial interaction; since being first
developed by Hansen (1959), it has been widely adopted in many forms
(Arranz-López et al., 2019; Cervero et al., 2002; Geurs and van Wee,
2004; Handy and Niemeier, 1997; Levinson, 1998; Paez, 2004). Next to
gravity-based approaches, another common type of accessibility
measurement are cumulative-opportunity aproaches in which access to
opportunities are evaluated by using travel distance or time threshold
to opportunities (Vickerman, 1974; Wachs and Kumagai, 1973). Though
gravity-based measures are argued to be more theoretically sound (Siddiq
and D. Taylor, 2021), results from the more simple-to-understand
cumulative-opportunity measures can correlate with gravity-based
accessibility when travel thresholds are correctly selected (El-Geneidy
and Levinson, 2006; Higgins, 2019; Kwan, 1998; Santana Palacios and
El-geneidy, 2022; Wang et al., 2021). Place-based accessibility analysis
offers a powerful tool to study the intersection between urban structure
and transportation infrastructure - however, the interpretability of the
output values can be challenging (Geurs and van Wee, 2004; Miller,
2018). A key issue is that accessibility measures are sensitive to the
number of opportunities in a region (e.g., a large city has more jobs
than a smaller city), and therefore raw outputs are not easily compared
across study areas (Allen and Farber, 2019).

The meaning of conventional gravity-based and cumulative-opportunity
accessibility raw outputs are unclear as they measure the
\emph{intensity of the possibility of interaction} (as defined by
Hansen, 1959) so categorical membership to high- through low-
accessibility to opportunities scores are assigned to the spatial unit
of analysis. For instance, in the study of accessibility to employment
by public transit in Metropolitan São Paulo Metropolitan Region,
Boisjoly et al. (2017) find that for every 1\% increase in
cumulative-opportunity accessibility score the probability of being in
informal job sector decreases by 3\% . However, this study does not
include the raw values as it can be assumed that primary use in
visualization is to identify region-relative hot- and cold- spots and
not the values themselves.

As a different example, in the work of Bocarejo S. and Oviedo H. (2012),
they include the raw gravity-based accessibility to employment values
for each community in Bogota. A similar interpretability issue arises:
what does it mean for the Zona Franca community and El Rincón community
to have 35,704 employment accessibility and 148,238 employment
accessibility (i.e., the number of potential job opportunities)
respectively? Once these values are normalized per capita, they
represent 0.87 and 0.86 accessibility per capita but, but as discussed
from the perspective of demand in Paez et al. (2019), opportunities are
multiple-counted per capita so normalizing per capita does not
consistently address this limitation. Though uses of gravity-based and
cumulative-opportunity accessibility measures in the work of Boisjoly et
al. (2017) and Bocarejo S. and Oviedo H. (2012) represent urban
structure and can help inform policy, the interpretation of the raw
magnitudes of the measures are unclear and may even be inaccurate when
applied to rival opportunities, like employment opportunities (Merlin
and Hu, 2017).

Put another way, conventional measures of accessibility do not capture
the \emph{competition} for opportunities but instead quantify access as
if every person can take every opportunity given their mobility
(Kelobonye et al., 2020; Paez et al., 2019). These conventional
approaches (i.e., non-competitive) are not necessarily problematic if
the opportunity of interest is non-rival, that is, if use by one unit of
population does not preclude use by another. For instance, national
parks with abundant space are seldom used to full capacity, so the
presence of some population does not exclude use by others. However,
inconsistent opportunity-adjustments can be more acute when
opportunities are \emph{rival}. For example, the work of Merlin and Hu
(2017) found using competitive gravity-based accessibility more
accurately reflects empirical access to employment opportunities in Los
Angelos than non-competitive methods. Though these rival-type
opportunities can still be modelled by conventional accessibility (e.g.,
jobs in Boisjoly et al. (2017) and Bocarejo S. and Oviedo H. (2012)),
the output values ultimately do not reflect the \emph{spatial
availability} of the opportunity.

There has been academic efforts to develop accessibility approaches
which consider competition. The first approach was introduced by Weibull
(1976) in which the distance decay of the supply of employment and the
demand for employment (by workers) was formulated under axiomatic
assumptions. This approach was then applied by Joseph and Bantock (1984)
in the context of healthcare, to quantify the availability of general
practioners in Canada. More recently, Shen (1998) re-created Weibull
(1976) formula and deconstructed it to consider accessibility for
different modes. These advances were reformatted and popularized as the
family of two-step floating catchment area (2SFCA) methods (Luo and
Wang, 2003) that have found widespread adoption for calculating
competitive accessibility to a variety of opportunities such as
healthcare, education, and food access (B. Y. Chen et al., 2020; Chen,
2019; Z. Chen et al., 2020; Yang et al., 2006; Ye et al., 2018). The
2SFCA method is mathematically equivalent to the works of Shen (1998)
and Weibull (1976).

Another approach which researchers have used to consider competition in
accessibility has been the imposition of constraints on the gravity
model to ensure potential interaction equals observed totals (i.e.,
population and/or opportunities). Based on Wilson's (1971) description
of the gravity-based modelled interaction, researchers can incorporate
constraints to ensure that the modeled origin-destination flows match
some known quantities in the data inputs. In this way, models can be
\textbf{singly-constrained} to match the row- or column-marginals (i.e.,
the population-trips produced or attracted, respectively),
\textbf{doubly-constrained} to match both marginals, or
\textbf{unconstrained} if neither population-trips produced or attracted
are preserved. For instance, in Shen (1998) work, he provides a proof
that demonstrates that the total sum of opportunities (not population)
in the network considered is preserved; this proof which demonstrates
that Shen-style accessibility is singly-constrained, is the basis of
\emph{spatial availability} and is discussed within this paper. Next,
Allen and Farber (2019) employed a doubly-constrained gravity-based
accessibility model as both the population and employment opportunity
counts are preserved within the accessibility outputs and thus can be
easily compared across regions. And as previously mentioned, Bocarejo S.
and Oviedo H. (2012) developed a detailed gravity-based accessibility
model to quantify the total accessibility to employment for each study
area community; this model can be interpreted as unconstrained since the
total number of opportunities (or population) are not preserved within
the accessibility outputs.

Using Wilson (1971)'s spatial interaction model classifications of
doubly-, singly- or unconstrained may be a useful to better interpreting
\emph{how} opportunities are counted in place-based measured and
\emph{how} competition is considered. In this way, the aim of this paper
is three-fold:

\begin{itemize}
\tightlist
\item
  First, we aim to demonstrate that Shen-style (and thus Weibull (1976))
  accessibility and the popular 2SFCA method are
  \emph{singly-constrained} from the perspective of opportunities
  allocated (i.e., population-trips produced ).
\item
  Second, we introduce a new measure, \emph{spatial availability}, as a
  more interpretable version of Shen-style accessibility, in which the
  opportunities in the system are preserved and proportionally allocated
  to each origin.
\item
  Third, we contrast \emph{spatial availability} with conventional
  gravity-based accessibility and demonstrate how it may be more
  intuitive for policy planners.
\end{itemize}

The contribution of this paper is thus to introduce and present spatial
availability alongside and in context with doubly-, unconstrained, and
other singly- constrained measures. Using spatial availability, we aim
to demonstrate that this singly-constrained measure proportionally
allocates (based on travel cost and population size) all opportunities
to the opportunity-seeking population. By allocating opportunities in a
proportional way in a single step, this measure considers competition
and avoids the issues that result from multiple allocation of the same
opportunities in \emph{unconstrained} accessibility analysis (i.e.,
Hansen-style accessibility). Spatial availability returns the value of
available opportunities per origin and can be effectively normalized as
a rate of available opportunities per opportunity-seeking population.
The normalized rate is equivalent to Shen-style accessibility thus can
be used as a benchmark value to compare \emph{available} opportunity
rates both inter- and intra-regionally as well as be used in the context
of opportunity provision assessment. This novel approach and clarifying
work comes at a time when the quantity and resolution of data is
exponentially increasing and the need to operationalize accessibility
methods in city-planning objectives is urgent.

This paper is split into four main parts. The first part describes a
re-newed interpretation of how congestion and/or competition are treated
in existing measures of singly-constrained, doubly-constrained, and
unconstrained accessibility. The second part introduces spatial
availability and uses a synthetic example to compare it to the
established measures discussed. In the third part, we then calculate,
compare, and contrast the spatial availability, unconstrained
accessibility (i.e., Hansen-style accessibility), and doubly-constrained
accessibility for 2016 employment data in the city of Toronto, Canada
(Transportation Tomorrow Survey (TTS)). The motivation of this part is
to demonstrate how constraints on accessibility distributes
opportunities and thus impacts interpretability. Finally, we conclude by
remarking on the conceptual limits of unconstrained accessibility
analysis, the computational burden of doubly-constrained accessibility
analysis and outline the advantages of the spatial availability measure
and the breadth of potential uses from the perspective of
opportunity-provision planning.

In the spirit of openness of research in the spatial sciences (Brunsdon
and Comber, 2021; Páez, 2021) this paper has a companion open data
product (Arribas-Bel et al., 2021), and all code will be available for
replicability and reproducibility purposes. We call for researchers to
examine our contribution and to re-examine the use of unconstrained,
singly-constrained, and doubly- constrained accessibility measures based
on the qualities of the opportunities and the populations in question.

\hypertarget{background}{%
\section{Re-framing accesssibility measures
interpretations}\label{background}}

We first describe unconstrained (Hansen, 1959), singly-constrained (Luo
and Wang, 2003; Shen, 1998), and doubly-constrained (Horner, 2004; Paez
et al., 2019), accessibility measures. Then present the synthetic
example introduced in Shen (1998) (slightly modified so the population
is greater than the job opportunities). Then we introduce the proposed
spatial availability measure, calculate the spatial availability values
as well as the established accessibility measures for the synthetic
example. We discuss how the interpretation of the resulting values from
the perspective of opportunity-provision and the impact that
opportunity-constraints have on interpretation. The synthetic example is
presented in Figure \ref{fig:plot-toy-example}, the results are
summarized in \textbf{Table XX}, and the detailed solutions are in the
\textbf{Appendix} for all measures.

\hypertarget{unconstrained-accessibility}{%
\subsection{Unconstrained
accessibility}\label{unconstrained-accessibility}}

Accessibility analysis stems from the foundational works of Harris
(1954) and Hansen (1959). From their seminal efforts, many accessibility
measures (excluding utility-based measures) have been derived,
particularly after the influential work of Wilson (1971) on the gravity
model. The model follows the formulation shown in Equation
(\ref{eq:conventional-accessibility}) and the solved synthetic example
is in \textbf{Table XX - left}.

\begin{equation}
\label{eq:conventional-accessibility}
A_i = \sum_{j=1}^JO_j \cdot f(c_{ij})
\end{equation}

\noindent where:

\begin{itemize}
\tightlist
\item
  \(A\) is accessibility.
\item
  \(i\) is a set of origin locations.
\item
  \(j\) is a set of destination locations.
\item
  \(O_j\) is the number of opportunities at location \(j\);
  \(\sum_j O_j\) is the total supply of opportunities in the study
  region.
\item
  \(c_{ij}\) is a measure of the cost of moving between \(i\) and \(j\).
\item
  \(f(\cdot)\) is an impedance function of \(c_{ij}\); it can take the
  form of any monotonically decreasing function chosen based on positive
  or normative criteria (Paez et al., 2012).
\end{itemize}

As formally defined, accessibility \(A_i\) is the weighted sum of
opportunities that can be reached from location \(i\), given the cost of
travel \(c_{ij}\). Summing the opportunities in the neighborhood of
\(i\), as determined by the impedance function \(f(\cdot)\), provides
estimates of the number of opportunities that can be reached from \(i\)
at a certain cost. The type of accessibility can be modified depending
on the impedance function; for example, the measure could be cumulative
opportunities (if \(f(\cdot)\) is a binary or indicator function e.g.,
El-Geneidy et al., 2016; Geurs and van Wee, 2004; Qi et al., 2018; Rosik
et al., 2021) or a gravity measure using an impedance function modeled
after any monotonically decreasing function (e.g., Gaussian, inverse
power, negative exponential, or log-normal, among others, see,
\emph{inter alia}, Kwan, 1998; Li et al., 2020; Reggiani et al., 2011;
Vale and Pereira, 2017). In practice, the accessibility measures derived
from many cumulative and gravity formulations tend to be highly
correlated with one another (Higgins, 2019; Kwan, 1998; Santana Palacios
and El-geneidy, 2022).

Gravity-based accessibility has been shown to be an excellent indicator
of the intersection between urban structure and transportation
infrastructure (Kwan, 1998; Reggiani et al., 2011; Shi et al., 2020).
However, beyond enabling comparisons of relative values they are not
highly interpretable on their own (Miller, 2018). To address this
interpretability issue, previous research has aimed to index and
normalize values on a per demand-population basis (e.g., Barboza et al.,
2021; Pereira et al., 2019; Wang et al., 2021). However, as recent
research on accessibility discusses (Allen and Farber, 2019; Kelobonye
et al., 2020; Merlin and Hu, 2017; Paez et al., 2019), these steps do
not truly adequately consider competition. In effect, when calculating
\(A_i\), every opportunity enters the weighted sum once for every origin
\(i\) that can reach it. Neglecting to constrain opportunity and
population counts (i.e., doubly-constrained) or just opportunity or just
population counts (i.e., single-constraint) in addition to obscuring the
interpretability of accessibility can bias the estimated landscape of
opportunity, as we will discuss later.

\hypertarget{singly-constrained-accessibility}{%
\subsection{Singly-constrained
accessibility}\label{singly-constrained-accessibility}}

Past research has considered competition by introducing demand-side
modifications to the Hansen-style accessibility. These modifications
consider spatially-distributed impacts of competition from the
perspective of opportunity-seekers. For example, the influential work of
Shen (1998) (and Weibull (1976); Joseph and Bantock (1984)) divides
conventional accessibility by the travel-cost adjusted population
seeking the opportunities in a given region. These works were
reformatted (remaining mathematically equivalent) and popularized by the
2-step floating catchment approach (2SFCA) introduced by Luo and Wang
(2003) which are widely used today.

The formulation of the 2SFCA approach is shown in step 1 (Equation
(\ref{eq:2SFCA-step1})) where the provider-to-population ratio (PPR)
\(R_j\) is calculated for each opportunity and then allocated to
populations based on travel cost \(f(\cdot)\) in step 2 (Equation
(\ref{eq:2SFCA-step2})).

\begin{equation}
\label{eq:2SFCA-step1}
R_{j} = \frac{O_{j}}{\sum_i P_{i} \cdot f(c_{ij})}\\
\end{equation}

\begin{equation}
\label{eq:2SFCA-step2}
A_{i} = {\sum_j R_{j} \cdot f(c_{ij})}\\
\end{equation}

\noindent where:

\begin{itemize}
\tightlist
\item
  \(A\) is accessibility.
\item
  \(i\) is a set of origin locations.
\item
  \(j\) is a set of destination locations.
\item
  \(O_j\) is the number of opportunities at location \(j\);
\item
  \(P_i\) is the population at location \(i\); \(\sum_j R_j\) is the
  total supply of opportunities in the study region.
\item
  \(R_j\) is the provider-to-population (PPR) ratio at location \(j\);
\item
  \(c_{ij}\) is a measure of the cost of moving between \(i\) and \(j\);
\item
  \(f(\cdot)\) is an impedance function of \(c_{ij}\).
\end{itemize}

It should be noted that both methods used in Shen (1998) and Luo and
Wang (2003) are also equivalent in the sense that the resulting values
are an artifact of the constrained opportunities (see proof in Shen
(1998)). Each resulting value, when multiplied by the population at that
origin and summed for the full study region, results in the total number
of opportunities in the full study region. This is to say, that the
total number of opportunities are constrained and fully preserved.

\hypertarget{doubly-constrained-accessibility}{%
\subsection{Doubly-constrained
accessibility}\label{doubly-constrained-accessibility}}

As shown by Paez et al. (2019), singly-constraining (referred to as
congestion) does not necessarily mean competition, as the same
population is claimed by multiple service centers and the same level of
service is given to multiple populations. Allen and Farber (2019) also
discusses the need to balance both the demand-side (opportunity-seekers)
and supply-side (opportunities) Hence, population and opportunity
constraints have been introduced to the Hansen-style accessibility to
consider spatially-distributed impacts of competition from both
opportunity-seekers and between opportunities. These modifications take
the form of inverse balancing factors and have been used in works such
as (Horner, 2004) and (Allen and Farber, 2019) from the perspective of
employment opportunities. These modifications, in an alternative way,
have also been taken by Paez et al. (2019) in their balanced 2-step
floating catchment approach (B2SFCA) within the health-care context.

For the method used by Allen and Farber (2019), the inverse balancing
factor for each origin is calculated through an iterative procedure
until convergence. The iterations seek to match the opportunities to the
population in the region where both are weighted by the travel cost
(impedance function). It requires that the total population and
opportunities are equal in the region but the mean accessibilities from
previous iterations can be included to standardize the imbalance. The
solved synthetic example is in \textbf{Table XX - middle}, and the
formulation of this method is as follows in Equation
(\ref{eq:Inverse-balancing-1}) and (\ref{eq:Inverse-balancing-2}).

\begin{equation}
\label{eq:Inverse-balancing-1}
A_{i} = \frac{\bar A^{o}}{\bar A^{c}}{\sum_{j=1}^{J} \frac{O_{j}f(c_{ij})}{B_{j}}}\\
\end{equation}

\begin{equation}
\label{eq:Inverse-balancing-2}
B_{i} = {\sum_{i=1}^{I} \frac{P_{i}f(c_{ij})}{A_{i}}}\\
\end{equation}

\noindent where: - \(B_{i}\) is the balancing factor; other variables
defined in the gravity model.

Though the unmodified Shen-style accessibility and 2SFCA are equivalent,
the inverse balanced modified accessibility (used by Allen and Farber
(2019)) is not equivalent to the B2SFCA of Paez et al. (2019). The
B2SFCA advances the 2SFCA by incorporating a demand-side balancing
factor to the PPR at each origin at both steps. The method results in a
consistent number of opportunities being assigned.

In the B2SFCA, the PPR \(R_{j}\) can be interpreted as the total number
of opportunities (i.e., jobs) accessible to the total
\emph{proportionally} travel-cost adjusted population at each
opportunity center. The PPR \(R_{j}\) is then allocated proportionally
based on travel cost, to each population center yielding \(A_{i}\). For
this reason, the sum of all \(A_{i}\) adds up to the same value as the
sum of all \(R_{j}\). Since PPR and the subsequent \(A_{i}\) are
proportionally allocated based travel costs, it should be noted that
\(A_{i}\) no longer considers \emph{potential} interaction as how it was
defined in the gravity model (Hansen, 1959) and instead represent the
allocation of PPR, based on travel time, to each population. This
measure introduces some consistency in how the PPR is calculated
(compared to the 2SFCA), but is still lacking interpretability in the
resulting values.

The solved synthetic example is in \textbf{Table XX - right}, and the
formulation of this method is as follows in Equation (\ref{eq:B2SFCA-1})
and (\ref{eq:B2SFCA-2}).

\begin{equation}
\label{eq:B2SFCA-1}
R_{j} = \frac{O_{j}}{\sum_i P_{i} \frac{f(c_{ij})}{\sum_j f(c_{ij})}}\\
\end{equation}

\begin{equation}
\label{eq:B2SFCA-2}
A_{i} = {\sum_j R_{j}\frac{f(c_{ij})}{\sum_j f(c_{ij})}}\\
\end{equation}

\hypertarget{introducing-spatial-availability-and-a-synthetic-example}{%
\section{Introducing spatial availability and a synthetic
example}\label{introducing-spatial-availability-and-a-synthetic-example}}

Here we introduce the spatial availability model formulation using the
synthetic example modified from Shen (1998) (Figure
\ref{fig:plot-toy-example}).

\begin{figure}

{\centering \includegraphics[width=1\linewidth]{images/plot-toy-example} 

}

\caption{\label{fig:plot-toy-example} Shen (1998) synthetic example with locations of employment centers, population centers, number of employment opportunities and population at centers, and travel time between population centers to employment centers between and to Urban, Suburban, and Satellite Town regions.}\label{fig:create-figure-with-toy-example3}
\end{figure}

We define spatial availability \(V_{i}\) as the number of opportunities
\(O\) that are proportionally allocated based on population and cost of
travel, for all origins \(i\) to all destinations \(j\).

This idea is reflected in Equation (\ref{eq:spatial-availability}),
where \(F^p_{i}\) is a population-based allocation factor that grants a
larger share of the existing opportunities to larger centers, and
\(F^c_{ij}\) is a transportation cost-based allocation factor that
grants a larger share of the existing opportunities to closer centers.
This is in line with the tradition of gravity modeling, and proposed
framework distinguishes between opportunities at a destination and
demand for opportunities at the origin.

\begin{equation}
\label{eq:spatial-availability}
V_{i} = O_j\frac{F^p_{i} \cdot F^c_{ij}}{\sum_{i=1}^K F^p_{i} \cdot F^c_{ij}}
\end{equation}

The terms in Equation \ref{eq:spatial-availability} are as follows:

\begin{itemize}
\tightlist
\item
  \(V_{i}\) is the spatial availability of opportunities in \(j\) to
  origin \(i\).
\item
  \(i\) is a set of origin locations in the region \(K\).
\item
  \(j\) is a set of destination locations in the region \(K\).
\item
  \(O_j\) is the number of opportunities at location \(j\) in the region
  \(K\).
\item
  \(F^p_{i}\) is a proportional allocation factor of the population in
  \(i\).
\item
  \(F^c_{ij}\) is a proportional allocation factor of travel cost for
  \(i\); it is a product of a monotonically decreasing (i.e., impedance)
  function associated with the cost of travel between \(i\) and \(j\).
\end{itemize}

Notice that, unlike \(A_i\) in Equation
(\ref{eq:conventional-accessibility}), the population in the region
enters the calculation of \(V_{i}\). It is important to detail the role
of the two proportional allocations factors in the formulation of
spatial availability. We begin by considering the population allocation
factor \(F^p_{i}\) followed by the role of the travel cost allocation
factor \(F^c_{ij}\); then we show how both allocation factors combine in
the final general form of spatial availability \(V_{i}\). The
calculation of spatial availability is introduced with a step-by-step
example for the three population centers (\(A\), \(B\), \(C\)) in the
role of demand (i.e., the number of individuals in the labor market who
`demand' employment) and three employment centers (\(1\), \(2\), \(3\))
in the role of opportunities.

\hypertarget{population-and-travel-cost-allocation-factors}{%
\subsection{Population and travel cost allocation
factors}\label{population-and-travel-cost-allocation-factors}}

We begin with allocation based on demand by population; consider an
employment center \(j\) with \(O_j\) jobs. In the general case where
there are \(K\) population centers in the region, we define the
following factor:

\begin{equation}
\label{eq:pop-alloc-factor}
F^p_{i} = \frac{P_{i}^\alpha}{\sum_{i=1}^K P_{i}^\alpha}
\end{equation}

The population allocation factor \(F^p_{i}\) corresponds to the
proportion of the population in origin \(i\) relative to the population
in the region. On the right hand side of the equation, the numerator
\(P_{i}\) is the population at origin \(i\) that is eligible for and
demands jobs \(j\). The summation in the denominator is over
\(i=1,\cdots,K\), the population at origins \(i\) in the region. To
modulate the effect of demand by population in this factor we include an
empirical parameter \(\alpha\) (i.e., \(\alpha <1\) places greater
weight on smaller centers relative to larger ones while \(\alpha>1\)
achieves the opposite effect). This population allocation factor
\(F^p_{i}\) can now be used to proportionally allocate a share of the
jobs at \(j\) to origins.

More broadly, since the factor \(F^p_{i}\) is a proportion, when it is
summed over \(i=1,\cdots,K\) it always equals to 1 (i.e.,
\(\sum_i^{K} F^p_{i} = 1\)). This is notable since the share of jobs at
each destination \(j\) allocated to (i.e., available to) each origin,
based on population, is equal to \(V^p_{i} = O_j \cdot F^p_{i}\). Since
the sum of \(F^p_{i}\) is equal to 1, it follows that
\(\sum_{i=1}^I V_{i} = O_j\). In other words, the number of
opportunities (jobs) across the region is preserved. The result is a
proportional allocation of jobs to origins based on the size of their
populations.

For simplicity, assume that \(\alpha=1\). The population allocation
factors \(F^p_{i}\) is as follows in Equation
(\ref{eq:pop-alloc-factor-2populations}).

\begin{equation}
\label{eq:pop-alloc-factor-2populations}
\begin{array}{l}
F^p_{1} = \frac{P_1 ^\alpha}{P_1^\alpha + P_2^\alpha + P_3^\alpha} = \frac{260}{260 + 255 + 495} = 0.257\\
F^p_{2} = \frac{P_2^\alpha}{P_1^\alpha + P_2^\alpha + P_3^\alpha}  = \frac{255}{260 + 255 + 495} = 0.252\\
F^p_{3} = \frac{P_3^\alpha}{P_1^\alpha + P_2^\alpha + P_3^\alpha}  = \frac{495}{260 + 255 + 495} = 0.490\\
\end{array}
\end{equation}

These \(F^p_{i}\) values can be used to find a \emph{partial} spatial
availability in which jobs are allocated proportionally to population;
this partial spatial availability \(V^p_{i}\) for each population center
is calculated as follows in Equation
(\ref{eq:pop-alloc-factor-SA-2populations}).

\begin{equation}
\label{eq:pop-alloc-factor-SA-2populations}
\begin{array}{l}
V^p_{1} = O_1 \cdot F^p_{1} + O_2 \cdot F^p_{1} = 750 \cdot 0.257 + 220 \cdot 0.257 = 249.29 \\
V^p_{2} = O_1 \cdot F^p_{2} + O_2 \cdot F^p_{2} = 750 \cdot 0.252 + 220 \cdot 0.252 = 244.44 \\
V^p_{3} = O_1 \cdot F^p_{3} + O_2 \cdot F^p_{3}= 750 \cdot 0.490 + 220 \cdot 0.490 = 475.30 \\
\end{array}
\end{equation}

When using only the proportional allocation factor \(F^p_{i}\) to
calculate spatial availability (differentiated here by being defined as
\(V^p_{i}\) instead of \(V_{i}\)), proportionally more jobs are
allocated to the bigger population center (i.e., 2 times more jobs as it
is 2 times larger in population). We can also see that the sum of
spatial availability for all population centers equals the total number
of opportunities.

Clearly, using only the proportional allocation factor \(F^p_{i}\) to
calculate spatial availability does not account for how far population
centers are from employment centers. It is the task of the second
allocation factor \(F^c_{ij}\) to account for the friction of distance,
as seen in Equation (\ref{eq:tcost-alloc-factor}).

\begin{equation}
\label{eq:tcost-alloc-factor}
F^c_{ij} = \frac{f(c_{ij})}{\sum_{i=1}^K f(c_{ij})}\\
\end{equation}

Travel cost allocation factor \(F^c_{ij}\) serves to proportionally
allocate more jobs to closer locations through an impedance function.
\(c_{ij}\) is the cost (e.g., the distance, travel time, etc.) to reach
employment center \(j\) from \(i\) and \(f(\cdot)\) is an impedance
function that depends on cost (\(c_{ij}\)).

To continue with the example, assume that the impedance function is a
exponential function with \(\beta=-0.00015\) and the distance from
population centers to employment centers is as shown in TABLE XX.
\(\beta\) modulates the steepness of the impedance effect and is
empirically determined in the case of positive accessibility, or set by
the analyst to meet a preset condition in the case of normative
accessibility (Paez et al., 2012). The proportional allocation factor
\(F^p_{i}\) for all population centers is defined in Equation
(\ref{eq:tcost-allocation-factor-2populations}).

\begin{equation}
\label{eq:tcost-allocation-factor-2populations}
\begin{array}{l}
F^c_{1,1} = \frac{\exp(\beta*2548.1)}{\exp(\beta *2548.1) + \exp(\beta *1314.1) + \exp(\beta *2170.2)} = 0.109\\
F^c_{2,1} = \frac{\exp(\beta *1314.1)}{\exp(\beta *2548.1) + \exp(\beta *1314.1) + \exp(\beta *2170.2)} = 0.697\\
F^c_{3,1} = \frac{\exp(\beta *2170.2)}{\exp(\beta *2548.1) + \exp(\beta *1314.1) + \exp(\beta *2170.2)} = 0.193\\
F^c_{1,2} = \frac{\exp(\beta*5419.1)}{\exp(\beta *5419.1) + \exp(\beta *2170.2) + \exp(\beta *1790.1)} = 0.004\\
F^c_{2,2} = \frac{\exp(\beta *4762.6)}{\exp(\beta *5419.1) + \exp(\beta *2170.2) + \exp(\beta *1790.1)} = 0.011\\
F^c_{3,2} = \frac{\exp(\beta *1790.1)}{\exp(\beta *5419.1) + \exp(\beta *2170.2) + \exp(\beta *1790.1)} = 0.984\\
\end{array}
\end{equation}

We can see, for instance, that the proportional allocation factor for
\(P_2\) is largest for \(E_1\) since the cost (i.e., distance) to
\(E_1\) is lowest. For \(E_2\), \(P_3\) has the largest proportional
allocation factor similarly because it is in the closest proximity.
Using the travel cost proportional allocation factors \(F^c_{ij}\) as
defined in Equation (\ref{eq:tcost-allocation-factor-2populations}), we
can calculate the spatial availability of jobs for each population
center based only on \(F^c_{ij}\) and the jobs available at each
employment center, as shown in Equation
(\ref{eq:tcost-allocation-factor-SA-2populations}).

\begin{equation}
\label{eq:tcost-allocation-factor-SA-2populations}
\begin{array}{l}
V^c_{1,1} = E_1 \cdot F^c_{1,1} = 750 \times 0.109 = 81.75\\
V^c_{2,1} = E_1 \cdot F^c_{2,1} = 750 \times  0.697 = 522.75\\
V^c_{3,1} = E_1 \cdot F^c_{3,1} = 750 \times  0.193 = 144.75\\
V^c_{1,2} = E_2 \cdot F^c_{1,2} = 220 \times 0.004 = 0.88\\
V^c_{2,2} = E_2 \cdot F^c_{2,2} = 220 \times  0.011 = 2.42\\
V^c_{3,2} = E_2 \cdot F^c_{3,2} = 220 \times  0.984 = 216.48\\
\end{array}
\end{equation}

For instance, spatial availability defined by \(F^c_{ij}\) only (i.e.,
\(V^c_{i}\)) allocates a largest share of jobs from \(E_1\) to \(P_2\)
since it is the closest. However, as previously discussed, \(P_2\) has a
relatively small population, so \(V^p_{2,1}\) is actually the smallest
value of any population center for \(E_1\). It is necessary to combine
both population and travel cost factors to better reflect demand; these
two components are in line with how demand is conventionally modelled in
accessibility calculations which are re-scaled on a per
demand-population basis or also consider competition (e.g., Allen and
Farber, 2019; Barboza et al., 2021; Yang et al., 2006). Fortunately,
since both \(F^c_{ij}\) and \(F^p_{i}\) preserve the total number of
opportunities as they independently sum to 1, they can be combined
multiplicatively to calculate the proposed spatial availability
\(V_{i}\) which considers demand to be based on both population and
travel cost.

\hypertarget{putting-spatial-availability-together}{%
\subsection{Putting spatial availability
together}\label{putting-spatial-availability-together}}

We can combine the proportional allocation factors by population
\(F^p_{i}\) and travel cost \(F^c_{ij}\) and calculate spatial
availability \(V_{i}\) as introduced in Equation
(\ref{eq:spatial-availability}) and repeated below:

\[
V_{i} = O_j\frac{F^p_{i} \cdot F^c_{ij}}{\sum_{i=1}^K F^p_{i} \cdot F^c_{ij}}
\]

The resulting spatial availability \(V_{i}\) is calculated for all
population centers is calculated in Equation (\ref{eq:SA-2populations}).

\begin{equation}
\label{eq:SA-2populations}
\begin{array}{l}

V_{1,1} = O_1\cdot \frac{F^p_{1,1} \cdot F^c_{1,1}}{F^p_{1,1} \cdot F^c_{1,1} + F^p_{2,1} \cdot F^c_{2,1} + F^p_{3,1} \cdot F^c_{3,1}} = 
750 \cdot \frac{0.26 \cdot 0.109}{0.26 \cdot 0.109 + 0.25 \cdot 0.697 + 0.49 \cdot 0.193} = 70.45\\
V_{2,1} = O_1\cdot \frac{F^p_{2,1} \cdot F^c_{2,1}}{F^p_{1,1} \cdot F^c_{1,1} + F^p_{2,1} \cdot F^c_{2,1} + F^p_{3,1} \cdot F^c_{3,1}} = 
750 \cdot \frac{0.25 \cdot 0.697}{0.26 \cdot 0.109 + 0.25 \cdot 0.697 + 0.49 \cdot 0.193} = 441.72\\
V_{3,1} = O_1\cdot \frac{F^p_{3,1} \cdot F^c_{3,1}}{F^p_{1,1} \cdot F^c_{1,1} + F^p_{2,1} \cdot F^c_{2,1} + F^p_{3,1} \cdot F^c_{3,1}} = 
750 \cdot \frac{0.49 \cdot 0.193}{0.26 \cdot 0.109 + 0.25 \cdot 0.697 + 0.49 \cdot 0.193} = 237.83\\

V_{1,2} = O_2\cdot \frac{F^p_{1,2} \cdot F^c_{1,2}}{F^p_{1,2} \cdot F^c_{1,2} + F^p_{2,2} \cdot F^c_{2,2} + F^p_{3,2} \cdot F^c_{3,2}} = 
220 \cdot \frac{0.26 \cdot 0.004}{0.26 \cdot 0.004 + 0.25 \cdot 0.011 + 0.49 \cdot 0.984} = 0.46\\
V_{2,2} = O_2\cdot \frac{F^p_{2,2} \cdot F^c_{2,2}}{F^p_{1,2} \cdot F^c_{1,2} + F^p_{2,2} \cdot F^c_{2,2} + F^p_{3,2} \cdot F^c_{3,2}} = 
220 \cdot \frac{0.25 \cdot 0.011}{0.26 \cdot 0.004 + 0.25 \cdot 0.011 + 0.49 \cdot 0.984} = 1.26\\
V_{3,2} = O_2\cdot \frac{F^p_{1,2} \cdot F^c_{1,2}}{F^p_{1,2} \cdot F^c_{1,2} + F^p_{2,2} \cdot F^c_{2,2} + F^p_{3,2} \cdot F^c_{3,2}} = 
220 \cdot \frac{0.49 \cdot 0.984}{0.26 \cdot 0.004 + 0.25 \cdot 0.011 + 0.49 \cdot 0.984} = 218.28\\
\end{array}
\end{equation}

Aggregating by population center gives the following values:

\begin{equation}
\label{eq:SA-2populations-2}
\begin{array}{l}
V_{1} = 70.45 + 0.46 = 70.91\\
V_{2} = 441.72 + 1.26 = 442.98\\
V_{3} = 237.83 + 218.28 = 456.11\\
\end{array}
\end{equation}

Considering both population and cost allocation factors in \(V_{i}\),
the jobs at \(E1\) that are allocated to all population centers are
still preserved (i.e., \(V_{1,1} + V_{2,1} + V_{3,1} = O_1\)).
Additionally, the sum of jobs at \(E2\) are also all preserved (i.e.,
\(V_{1,2} + V_{2,2} + V_{3,2} = O_2\)). Thus the sum of \(V_{i}\) equals
the sum of opportunities (i.e., ) Notice that \(V_{i}\), allocates a
number of jobs to \(P_1\), \(P_2\), and \(P_3\) is between the values
allocated in \(V^p_{i}\) and \(V^c_{i}\).

When comparing \(V_i\) to the singly-constrained gravity model (see
Wilson (1971)), \(V_i\) is the result of constraining \(A_i\) to match
one of the marginals in the origin-destination table, the known total of
opportunities. Since the sum of opportunities is preserved in the
procedures above, it is possible to calculate an interpretable measure
of spatial availability per capita (lower-case \(v_i\)) as shown in
Equation (\ref{eq:SA-per-capita}).

\begin{equation}
\label{eq:SA-per-capita}
v_i = \frac{V_i}{P_i}
\end{equation}

To complete the illustrative example, the per capita spatial
availability of jobs is calculated in Equation
(\ref{eq:SA-per-capita-2populations}).

\begin{equation}
\label{eq:SA-per-capita-2populations}
\begin{array}{l}
v_{1} = \frac{V_{1,1} + V_{1,2}}{P_1} =  \frac{70.91}{260} = 0.272\\
v_{2} =  \frac{V_{2,1} + V_{2,2}}{P_2} =  \frac{442.98}{255} = 1.737\\
v_{3} =  \frac{V_{3,1} + V_{3,2}}{P_3} =  \frac{456.11}{495} = 0.921\\
\end{array}
\end{equation}

We can see that since \(P_2\) is closest to \(E1\), is similarly spaced
out from \(P1\) and \(P2\), and is a smaller population center thus
having less competition, \(P_2\) benefits with a higher spatial
availability of jobs per job-seeking population. We can also compare
these values to the overall ratio of jobs-to-population in this region
of two job center and three population centers is
\(\frac{750+220}{260+255+495}=\) 0.96 jobs per person.

\hypertarget{discusion-on-established-accessibility-measures-and-spatial-availability}{%
\subsection{Discusion on established accessibility measures and spatial
availability}\label{discusion-on-established-accessibility-measures-and-spatial-availability}}

Table \ref{tab:synthetic-example} contains the output from all the
measures reviewed above.

 
  \providecommand{\huxb}[2]{\arrayrulecolor[RGB]{#1}\global\arrayrulewidth=#2pt}
  \providecommand{\huxvb}[2]{\color[RGB]{#1}\vrule width #2pt}
  \providecommand{\huxtpad}[1]{\rule{0pt}{#1}}
  \providecommand{\huxbpad}[1]{\rule[-#1]{0pt}{#1}}

\begin{table}[ht]
\begin{centerbox}
\begin{threeparttable}
\captionsetup{justification=centering,singlelinecheck=off}
\caption{Summary description of synthetic example}
 \label{tab:synthetic-example}
\setlength{\tabcolsep}{0pt}
\begin{tabularx}{1\textwidth}{p{0.125\textwidth} p{0.125\textwidth} p{0.125\textwidth} p{0.125\textwidth} p{0.125\textwidth} p{0.125\textwidth} p{0.125\textwidth} p{0.125\textwidth}}


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedright \textbf{Origin}\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedright \textbf{Dest.}\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft \textbf{TT}\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft \textbf{Pop.}\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft \textbf{Jobs}\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft \textbf{A\_i}\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft \textbf{S\_i}\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft \textbf{BFCA\_i}\huxbpad{6pt}}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}-}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedright 1\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 15\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 100000\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedright 2\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 30\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 100000\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\multirow[t]{-3}{*}[0ex]{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedright A\huxbpad{6pt}}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedright 3\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 100\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\multirow[t]{-3}{*}[0ex]{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 60000\huxbpad{6pt}}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 10000\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\multirow[t]{-3}{*}[0ex]{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 27292.18\huxbpad{6pt}}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\multirow[t]{-3}{*}[0ex]{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 1.17\huxbpad{6pt}}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\multirow[t]{-3}{*}[0ex]{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 1.17\huxbpad{6pt}}}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}-}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedright 1\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 30\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 100000\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedright 2\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 15\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 100000\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\multirow[t]{-3}{*}[0ex]{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedright B\huxbpad{6pt}}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedright 3\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 100\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\multirow[t]{-3}{*}[0ex]{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 160000\huxbpad{6pt}}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 10000\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\multirow[t]{-3}{*}[0ex]{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 27292.18\huxbpad{6pt}}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\multirow[t]{-3}{*}[0ex]{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 0.81\huxbpad{6pt}}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\multirow[t]{-3}{*}[0ex]{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 0.81\huxbpad{6pt}}}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}-}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedright 1\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 100\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 100000\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedright 2\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 100\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 100000\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\multirow[t]{-3}{*}[0ex]{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedright C\huxbpad{6pt}}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedright 3\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 15\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\multirow[t]{-3}{*}[0ex]{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 10000\huxbpad{6pt}}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 10000\huxbpad{6pt}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\multirow[t]{-3}{*}[0ex]{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 2240.38\huxbpad{6pt}}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\multirow[t]{-3}{*}[0ex]{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 1.00\huxbpad{6pt}}}} &
\multicolumn{1}{p{0.125\textwidth}!{\huxvb{0, 0, 0}{0}}}{\multirow[t]{-3}{*}[0ex]{\hspace{6pt}\parbox[b]{0.125\textwidth-6pt-6pt}{\huxtpad{6pt + 1em}\raggedleft 1.00\huxbpad{6pt}}}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}->{\huxb{0, 0, 0}{0.4}}-}
\arrayrulecolor{black}
\end{tabularx}
\end{threeparttable}\par\end{centerbox}

\end{table}
 

For instance, from Figure \ref{fig:plot-toy-example}, \(A\) has equal
accessibility (27,292 potential jobs) as \(B\) despite \(A\) having a
three times smaller population. On the other hand, the isolated
satellite town of \(C\) has low accessibility (2240 potential jobs) but
it is still better than \emph{zero} and it has a small population. It is
difficult to determine which accessibility values indicate excellent,
good, or only fair accessibility access? What does it \emph{mean} for a
location to have accessibility to so many jobs?

To address this interpretability issue, previous research has aimed to
index and normalize values on a per demand-population basis (e.g.,
Barboza et al., 2021; Pereira et al., 2019; Wang et al., 2021). However,
as recent research on accessibility discusses (Allen and Farber, 2019;
Kelobonye et al., 2020; Merlin and Hu, 2017; Paez et al., 2019), these
steps do not truly address competition. In effect, when calculating
\(A_i\), every opportunity enters the weighted sum once for every origin
\(i\) that can reach it. Put another way, if the Suburban region \(A\)
increases its population and all employment centers and other population
centers are kept steady, \(A\) will have just as high an accessibility
score. There is a lurking assumption in this process that all
opportunities are potentially available to anyone from any origin
\(i=1,\cdots,n\) who can reach them: in other words, opportunities are
assumed to be non-rival and inexhaustible. This multiplication of the
opportunities means that competition is not really present, and \(A_i\)
does not consider that neighbouring population centers are seeking the
same exhaustible opportunities. Neglecting to constrain opportunity
counts (i.e., single-constraint) in addition to obscuring the
interpretability of accessibility can also bias the estimated landscape
of opportunity, as we will discuss later on in the paper.

We see that the PPR \(R_{j}\) for each employment center can be
interpreted as the total number of jobs accessible to the total
travel-cost adjusted population. This step recognizes that not all
opportunities can be distributed to the entire population evenly since
not \emph{all} opportunities can be reached by \emph{all} population
centers. It is assumed that all population and employment centers are in
the same catchment.

In step two, \(S_{i}\) values represent the travel-cost adjusted PPR for
each population center. Put another way, here \(S_{A}\), \(S_{B}\), and
\(S_{C}\) values represent the number of jobs accessible to each
population center after being travel-cost adjusted from both the
opportunities-perspective and population-perspective. The value could
theoretically be on a scale of 0 to the maximum total number of PPR in
the catchment (i.e., \(f(c_{ij})=0\) to \(f(c_{ij})=1\)); in this case
that value is 4.683 jobs per person.

\hypertarget{empirical-example-of-toronto}{%
\section{Empirical example of
Toronto}\label{empirical-example-of-toronto}}

In this section we use population and employment data from the Golden
Horseshoe Area (GGH). This is the largest metropolitan region in Canada
and includes the cities of Toronto and Hamilton. We calculate gravity
accessibility, XXX, and the proposed spatial availability for Toronto
after introducing the data used and calibrating an impedance function.

\hypertarget{data}{%
\subsection{Data}\label{data}}

Population and employment data are drawn from the 2016 Transportation
Tomorrow Survey (TTS). This survey collects representative urban travel
information from 20 municipalities contained within the GGH area in the
southern part of Ontario, Canada (see Figure
\ref{fig:TTS-16-survey-area}) (Data Management Group, 2018). The data
set includes Traffic Analysis Zones (TAZ) (n=3,764), the number of jobs
(n=3,081,885) and workers (n=3,446,957) at each origin and destination.
The TTS data is based on a representative sample of between 3\% to 5\%
of households in the GGH and is weighted to reflect the population
covering the study area has a whole (Data Management Group, 2018).

To generate the travel cost for these trips, travel times between
origins and destinations are calculated for car travel using the R
package \{r5r\} (Rafael H. M. Pereira et al., 2021) with a street
network retrieved from OpenStreetMap for the GGH area. A the 3 hr travel
time threshold was selected as it captures 99\% of population-employment
pairs (see the travel times summarized in Figure
\ref{fig:TTS-16-survey-area}). This method does not account for traffic
congestion or modal split, which can be estimated through other means
(e.g., Allen and Farber, 2021; Higgins et al., 2021). For simplicity, we
carry on with the assumption that all trips are taken by car in
uncongested travel conditions.

All data and data preparation steps are documented and can be freely
explored in the companion open data product
\href{https://github.com/soukhova/TTS2016R}{\{TTS2016R\}}.

\begin{figure}

{\centering \includegraphics[width=0.8\linewidth]{images/TTS16-survey-area} 

}

\caption{\label{fig:TTS-16-survey-area}TTS 2016 study area (GGH, Ontario, Canada) along with the descriptive statistics of the trips, calculated origin-destination car travel time (TT), workers per TAZ, and jobs per TAZ. Contains 20 regions (black boundaries) and sub-regions (dark gray boundaries).}\label{fig:TTS-16-survey-area}
\end{figure}

\hypertarget{calibration-of-an-impedance-function}{%
\subsection{Calibration of an impedance
function}\label{calibration-of-an-impedance-function}}

In the synthetic example introduced in a preceding section, a negative
exponential function with an arbitrary parameter was used. For the
empirical example, we calibrate an impedance function on the trip length
distribution (TLD) of commute trips. Briefly, a TLD represents the
proportion of trips that are taken at a specific travel cost (e.g.,
travel time); this distribution is commonly used to derive impedance
functions in accessibility research (Batista et al., 2019; Horbachov and
Svichynskyi, 2018).

The empirical and theoretical TLD for this data set are represented in
the top-left panel of Figure \ref{fig:TLD-Gamma-plot}. Maximum
likelihood estimation and the Nelder-Mead method for direct optimization
available within the \{fitdistrplus\} package (Delignette-Muller and
Dutang, 2015) were used. Based on goodness-of-fit criteria and
diagnostics seen in Figure \ref{fig:TLD-Gamma-plot}, the gamma
distribution was selected (also see Figure \ref{fig:plot-cullen-frey} in
Appendix XX).

\begin{verbatim}
[1] 3069541
\end{verbatim}

\begin{figure}

{\centering \includegraphics[width=0.8\linewidth]{images/impedance_function} 

}

\caption{\label{fig:TLD-Gamma-plot}Car trip length distribution and calibrated gamma distribution impedance function (red line) with associated Q-Q and P-P plots. Based on TTS 2016.}\label{fig:TLD-Gamma-plot}
\end{figure}

The gamma distribution takes the following general form where the
estimated `shape' is \(\alpha=\) 2.019, the estimated `rate' is
\(\beta =\) 0.094, and \(\Gamma(\alpha)\) is defined in Equation
(\ref{gamma-dist}).

\begin{equation}
\label{gamma-dist}
\begin{array}{l} 
f(x, \alpha, \beta) = \frac {x^{\alpha-1}e^{-\frac{x}{\beta}}}{ \beta^{\alpha}\Gamma(\alpha)} \quad \text{for } 0 \leq x \leq \infty\\

\Gamma(\alpha) =  \int_{0}^{\infty} x^{\alpha-1}e^{-x} \,dx\\
\end{array}
\end{equation}

\hypertarget{measuring-access-to-jobs-in-toronto}{%
\subsection{Measuring access to jobs in
Toronto}\label{measuring-access-to-jobs-in-toronto}}

Toronto is the largest city in the GGH and represents a significant
subset of workers and jobs in the GGH; 31\% of workers in the GGH travel
to jobs in Toronto and 40\% of jobs are located within Toronto.

\begin{figure}
\includegraphics[width=1\linewidth]{Spatial-Availability-Refreshed_files/figure-latex/plot-access-SA-TO-1} \caption{\label{fig:plot-access-SA-TO}Calculated accessibility (top) and spatial availability (bottom) of employment from origins in destinations and origins in Toronto. Greyed out TAZ represent null accessibility and spatial availability values.}\label{fig:plot-access-SA-TO}
\end{figure}

To enhance the interpretability, spatial availability can be normalized
to provide more meaningful insight into how many jobs are
\emph{available} on average for each TAZ. This normalization, shown in
Figure \ref{fig:plot-avail-GGH-TTS-per-worker}, demonstrates which TAZ
have above (reds) and below (blue) the average available jobs per worker
in the GGH (1.17). Similar to the spatial availability plot of the GGH
jobs in Figure \ref{fig:plot-access-SA-GGH-TTS}, we can see that many
average or above average jobs per worker TAZ (whites and reds) are
present in southern Peel and Halton (south-west of Toronto), Waterloo
and Brantford (even more south-west of Toronto), and Hamilton and
Niagara (south of Toronto), however, the distribution is uneven and many
TAZ within these areas do have below average values (blues).

Interestingly, when considering \emph{competitive} job access, many
areas outside of Toronto have similar jobs per worker values as TAZ in
Toronto. This is contrary to the notion that since Toronto has high job
access it has a significant density of employment opportunities in the
GGH. Not all jobs in Toronto are \emph{available} since Toronto has a
high density of \emph{competition} in addition to density of jobs
opportunities. For instance, urban centers outside of Toronto such as
those found in Brantford, Guelph, southern Peel, Halton, and Niagara
have TAZ which are far above the the TTS average jobs per worker and
higher than TAZ within Toronto. High job access is not seen in the
accessibility plot which suggests that these less densely populated
urban centers may have sufficient employment opportunities for their
populations; this finding is obscured when only considering the
accessibility measure for job access as will be later discussed.

It is also worth noting that there is almost two times more jobs per
worker in the GGH jobs spatial availability results than the GGH Toronto
spatial availability results. This suggests that all GGH people who work
in the city of Toronto, on average, face more competition for jobs than
all GGH people who work anywhere in the GGH .

\begin{figure}
\includegraphics[width=1\linewidth]{Spatial-Availability-Refreshed_files/figure-latex/plot-avail-TO-per-worker-1} \caption{\label{fig:plot-avail-TO-per-worker}Spatial availability per worker, from origins to job opportunities in Toronto.}\label{fig:plot-avail-TO-per-worker}
\end{figure}

\newpage

\hypertarget{discussion-and-conclusions}{%
\section{Discussion and Conclusions}\label{discussion-and-conclusions}}

\hypertarget{appendix-a-step-by-step-accessibility-calculations-for-synthetic-example}{%
\section{Appendix A: Step-by-step accessibility calculations for
synthetic
example}\label{appendix-a-step-by-step-accessibility-calculations-for-synthetic-example}}

Details for the synthetic example:

\begin{table}

\caption{\label{tab:toy-example-table-appendix}\label{tab:toy-example}Summary description of synthetic example}
\centering
\begin{tabular}[t]{llrrr}
\toprule
Origin & Destination & Travel Time & Population & Jobs\\
\midrule
A & 1 & 15 & 60000 & 100000\\
A & 2 & 30 & 60000 & 100000\\
A & 3 & 100 & 60000 & 10000\\
B & 1 & 30 & 160000 & 100000\\
B & 2 & 15 & 160000 & 100000\\
\addlinespace
B & 3 & 100 & 160000 & 10000\\
C & 1 & 100 & 10000 & 100000\\
C & 2 & 100 & 10000 & 100000\\
C & 3 & 15 & 10000 & 10000\\
\bottomrule
\end{tabular}
\end{table}

\noindent and: \[
\beta = -0.1 \space in \space f(c_{ij}) = exp(\beta *tt_{ij})
\]

\hypertarget{conventional-gravity-accessibiliy}{%
\subsection{Conventional gravity
accessibiliy}\label{conventional-gravity-accessibiliy}}

\[
A_i = \sum_{j=1}^JO_j \cdot f(c_{ij})
\]

Solved in one step: \[
\sum_{j=1}^JO_j = E1 + E2 =  750 + 220 = 970 \space jobs
\]

\begin{equation}
\begin{array}{l}
A_{A} = 100000 \cdot \exp(\beta*15) + 100000 \cdot \exp(\beta*30) + 10000 \cdot \exp(\beta*100) = 27292 \\
A_{B} = 100000 \cdot \exp(\beta*30) + 100000 \cdot \exp(\beta*15) + 10000 \cdot \exp(\beta*100) = 27292 \\
A_{C} = 100000 \cdot \exp(\beta*100) + 100000 \cdot \exp(\beta*100) + 10000 \cdot \exp(\beta*100) = 2240
\end{array}
\end{equation}

\(A_{A}\), \(A_{B}\), and \(A_{C}\) values represent the number of
travel-cost adjusted opportunities accessible to each population.
Specifically, only a proportion of opportunities are allocated to
population centers based on their travel cost value (higher the travel
cost lower the number of opportunities). The population is not
considered in this measure and the allocation of opportunities is not
constrained, it is only adjusted based on the weight of the travel cost.
With our negative exponential distance decay, accessibility can be as
high as 210,000 (the total number of opportunities in the region) and as
low as essentially 0.

However, in many instances being close to opportunities doesn't
necessarily mean much practically to an individual nor can this scale of
0 to the maximum number of total opportunities in the region be
operationalized by decision-makers. However, correlates have been found
so it is a strong indicator of urban structure, but practically what
does it mean for an individual to live in a population center of
\(A_{C} =\) 2,240 potential job opportunities? On a scale of 0 to
210,000 (\(f(c_{ij})=0\) to \(f(c_{ij})=1\)), this value is low but of
the three population centers it is around average. However, \(A_{B}\)
also has the largest population of all population centers. It has a
population that is three times the population center of \(A_{A}\) but an
accessibility value that is equal to \(A_{A}\)'s accessibility value.
Does it make sense that in both population centers, the accessibility is
equal or should it be adjusted based on population? Adjusting based on
population is not equivalent as both centers have different travel costs
to a different magnitude of opportunities. From this perspective,
competitive measures such as the FCA were introduced with the most
recently popularized 2SFCA is discussed as follows.

\hypertarget{step-floating-catchment-approach-2sfca}{%
\subsection{2 step floating catchment approach
(2SFCA)}\label{step-floating-catchment-approach-2sfca}}

Step one:

\begin{equation}
\begin{array}{l}
R_{j} = \frac{O_{j}}{\sum_i P_{i} \cdot f(c_{ij})}\\

R_{1} = \frac{100000}{60000 \cdot \exp(\beta*15) + 160000 \cdot \exp(\beta*30) + 10000 \cdot \exp(\beta*100)} = 4.683 \\
R_{2} = \frac{100000}{60000 \cdot \exp(\beta*30) + 160000 \cdot \exp(\beta*15) + 10000 \cdot \exp(\beta*100)} = 2.584 \\
R_{3} = \frac{10000}{60000 \cdot \exp(\beta*100) + 160000 \cdot \exp(\beta*100) + 10000 \cdot \exp(\beta*15)} = 4.462 \\
\end{array}
\end{equation}

Step two:

\begin{equation}
\begin{array}{l}
S_{i} = {\sum_j R_{j} \cdot f(c_{ij})}\\
S_{A} = 4.683 \cdot \exp(\beta*15) + 2.584 \cdot \exp(\beta*30) + 4.462 \cdot \exp(\beta*100) = 1.174 \\
S_{B} = 4.683 \cdot \exp(\beta*30) + 2.584 \cdot \exp(\beta*15) + 4.462 \cdot \exp(\beta*100) = 0.810 \\
S_{C} = 4.683 \cdot \exp(\beta*100) + 2.584 \cdot \exp(\beta*100) + 4.462 \cdot \exp(\beta*15) = 0.996
\end{array}
\end{equation}

We see that the PPR \(R_{j}\) for each employment center can be
interpreted as the total number of jobs accessible to the total
travel-cost adjusted population. This step recognizes that not all
opportunities can be distributed to the entire population evenly since
not \emph{all} opportunities can be reached by \emph{all} population
centers. It is assumed that all population and employment centers are in
the same catchment.

In step two, \(S_{i}\) values represent the travel-cost adjusted PPR for
each population center. Put another way, here \(S_{A}\), \(S_{B}\), and
\(S_{C}\) values represent the number of jobs accessible to each
population center after being travel-cost adjusted from both the
opportunities-perspective and population-perspective. The value could
theoretically be on a scale of 0 to the maximum total number of PPR in
the catchment (i.e., \(f(c_{ij})=0\) to \(f(c_{ij})=1\)); in this case
that value is 4.683 jobs per person.

It may seem that this method locates opportunities and population in an
unconstrained manner, but it is in fact constrained from the
opportunities perspective. See the proof below on how 2SFCA (and Shen
(1998) method) cancels out an equals Spatial Availability.

\hypertarget{proof-spatial-availability-cancels-out-into-shen-style-accessibility}{%
\subsubsection{Proof: Spatial availability cancels out into Shen-style
accessibility}\label{proof-spatial-availability-cancels-out-into-shen-style-accessibility}}

Population allocation factor:

\(F^p_{ij} = \frac{P_{i\in r}^\alpha}{\sum_{i}^K P_{i\in r}^\alpha}\)

\(F^p_{A} = \frac{P_{A}^\alpha}{P_{A}^\alpha + P_{B}^\alpha + P_{C}^\alpha}\)

Cost allocation factor:

\(F^c_{ij} = \frac{f(c_{ij})}{\sum_{i=A}^K f(c_{ij})}\)

\(F^c_{A1} = \frac{f(c_{A1})}{f(c_{A1})+f(c_{B1})+f(c_{C1})}\)
\(F^c_{B1} = \frac{f(c_{A2})}{f(c_{A2})+f(c_{B2})+f(c_{C2})}\)
\(F^c_{C1} = \frac{f(c_{A3})}{f(c_{A3})+f(c_{B3})+f(c_{C3})}\)

Now let's put it together with P, and see how the denominators end up
cancelling out:

\(v_{i} = \sum_{j}\frac{O_j}{P_{i\in r}^\alpha}\frac{\frac{P_{i\in r}^\alpha}{\sum_{i}^K P_{i\in r}^\alpha} \cdot \frac{f(c_{ij})}{\sum_{i}^K f(c_{ij})}}{\sum_{i}^K \frac{P_{i\in r}^\alpha}{\sum_{i}^K P_{i\in r}^\alpha} \cdot \frac{f(c_{ij})}{\sum_{i}^K f(c_{ij})}}\)

\(v_{A} = \frac{O_1}{P_{A}^\alpha}(\frac{\frac{P_{A}^\alpha}{P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha} \cdot \frac{f(c_{A1})}{f(c_{A1})+f(c_{B1})+f(c_{C1})}}{\frac{P_{A}^\alpha}{P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha} \cdot \frac{f(c_{A1})}{f(c_{A1})+f(c_{B1})+f(c_{C1})} + \frac{P_{A}^\alpha}{P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha} \cdot \frac{f(c_{B1})}{f(c_{A1})+f(c_{B1})+f(c_{C1})}+ \frac{P_{A}^\alpha}{P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha} \cdot \frac{f(c_{C1})}{f(c_{A1})+f(c_{B1})+f(c_{C1})}}) +\)

\(\frac{O_2}{P_{A}^\alpha}(\frac{\frac{P_{A}^\alpha}{P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha} \cdot \frac{f(c_{A2})}{f(c_{A2})+f(c_{B2})+f(c_{C2})}}{\frac{P_{A}^\alpha}{P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha} \cdot \frac{f(c_{A2})}{f(c_{A2})+f(c_{B2})+f(c_{C2})} + \frac{P_{A}^\alpha}{P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha} \cdot \frac{f(c_{B2})}{f(c_{A2})+f(c_{B2})+f(c_{C2})}+\frac{P_{A}^\alpha}{P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha} \cdot \frac{f(c_{C2})}{f(c_{A2})+f(c_{B2})+f(c_{C2})}} )+\)

\(\frac{O_3}{P_{A}^\alpha}(\frac{\frac{P_{A}^\alpha}{P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha} \cdot \frac{f(c_{A3})}{f(c_{A3})+f(c_{B3})+f(c_{C3})}}{\frac{P_{A}^\alpha}{P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha} \cdot \frac{f(c_{A3})}{f(c_{A3})+f(c_{B3})+f(c_{C3})} + \frac{P_{A}^\alpha}{P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha} \cdot \frac{f(c_{B3})}{f(c_{A3})+f(c_{B3})+f(c_{C3})}+\frac{P_{A}^\alpha}{P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha} \cdot \frac{f(c_{C3})}{f(c_{A3})+f(c_{B3})+f(c_{C3})}} )\)

First, notice how the denominator on the denominator is the same across
the summation? Let's simplify it:

\(v_{A} = \frac{O_1}{P_{A}^\alpha}(\frac{\frac{P_{A}^\alpha}{P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha} \cdot \frac{f(c_{A1})}{f(c_{A1})+f(c_{B1})+f(c_{C1})}}{\frac{P_{A}^\alpha \cdot f(c_{A1}) + P_{A}^\alpha \cdot f(c_{B1}) + P_{A}^\alpha \cdot f(c_{C1})}{(P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha) \cdot (f(c_{A1})+f(c_{B1})+f(c_{C1}))}}) +\)
\(\frac{O_2}{P_{A}^\alpha}(\frac{\frac{P_{A}^\alpha}{P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha} \cdot \frac{f(c_{A2})}{f(c_{A2})+f(c_{B2})+f(c_{C2})}}{\frac{P_{A}^\alpha \cdot f(c_{A2}) + P_{A}^\alpha \cdot f(c_{B2}) + P_{A}^\alpha \cdot f(c_{C2})}{(P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha) \cdot (f(c_{A2})+f(c_{B2})+f(c_{C2}))}}) +\)
\(\frac{O_3}{P_{A}^\alpha}(\frac{\frac{P_{A}^\alpha}{P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha} \cdot \frac{f(c_{A3})}{f(c_{A3})+f(c_{B3})+f(c_{C3})}}{\frac{P_{A}^\alpha \cdot f(c_{A3}) + P_{A}^\alpha \cdot f(c_{B3}) + P_{A}^\alpha \cdot f(c_{C3})}{(P_{A}^\alpha+P_{B}^\alpha+P_{C}^\alpha) \cdot (f(c_{A3})+f(c_{B3})+f(c_{C3}))}} )\)

See how the denominator of the denominator is the same as the
denominator of the numerator's denominator for each J (J=1, J=2, and
J=3)? Let's cancel those out and simplify:

\(v_{A} = \frac{O_1}{P_{A}^\alpha}(\frac{P_{A}^\alpha \cdot f(c_{A1})}{P_{A}^\alpha \cdot f(c_{A1}) + P_{A}^\alpha \cdot f(c_{B1}) + P_{A}^\alpha \cdot f(c_{C1})} +\)
\(\frac{O_2}{P_{A}^\alpha}\frac{P_{A}^\alpha \cdot f(c_{A2})}{P_{A}^\alpha \cdot f(c_{A2}) + P_{A}^\alpha \cdot f(c_{B2}) + P_{A}^\alpha \cdot f(c_{C2})} +\)
\(\frac{O_3}{P_{A}^\alpha}\frac{P_{A}^\alpha \cdot f(c_{A3})}{P_{A}^\alpha \cdot f(c_{A3}) + P_{A}^\alpha \cdot f(c_{B3}) + P_{A}^\alpha \cdot f(c_{C3})} )\)

Next, see how we can cancel out the \(P_{A}^\alpha\)? Let's do that.

\(v_{A} = O_1(\frac{f(c_{A1})}{P_{A}^\alpha \cdot f(c_{A1}) + P_{B}^\alpha \cdot f(c_{B1}) + P_{C}^\alpha \cdot f(c_{C1})} + O_2\frac{f(c_{A2})}{P_{A}^\alpha \cdot f(c_{A2}) + P_{B}^\alpha \cdot f(c_{B2}) + P_{C}^\alpha \cdot f(c_{C2})} + O_3\frac{f(c_{A3})}{P_{A}^\alpha \cdot f(c_{A3}) + P_{B}^\alpha \cdot f(c_{B3}) + P_{C}^\alpha \cdot f(c_{C3})} )\)

\hypertarget{balanced-2-step-floating-catchment-approach-b2sfca}{%
\subsection{balanced 2 step floating catchment approach
(B2SFCA)}\label{balanced-2-step-floating-catchment-approach-b2sfca}}

As discussed by Paez et al. (2019), in the 2SFCA, the PPR calculation in
the first step and allocation of PPR to origins in the second step is
not \emph{proportional} to the total population seeking opportunities.
Though the `potential' for interaction is being consistently allocated
in these two steps, when looking to decipher the meaning of the measure
from the perspective of allocation, the resulting values are difficult
to interpret. This issue of interpretability has been attempted to be
remedied by adjusting the population and opportunities in both steps by
a \emph{proportional} travel cost in the B2SFCA as follows.

Step one:

\begin{equation}
\begin{array}{l}

R_{j} = \frac{O_{j}}{\sum_i P_{i} \frac{f(c_{ij})}{\sum_j f(c_{ij})}}\\

R_{1} = \frac{100000}{60000 \frac{\exp(\beta *15)}{\exp(\beta *15) + \exp(\beta*30) + \exp(\beta*100)} + 160000 \frac{\exp(\beta *30)}{\exp(\beta *15) + \exp(\beta*30) + \exp(\beta*100)} + 10000 \frac{\exp(\beta *100)}{\exp(\beta *15) + \exp(\beta*30) + \exp(\beta*100)}}\\
R_{1} = 1.278\\

R_{2} = \frac{100000}{60000 \frac{\exp(\beta *30)}{\exp(\beta *15) + \exp(\beta*30) + \exp(\beta*100)} + 160000 \frac{\exp(\beta *15)}{\exp(\beta *15) + \exp(\beta*30) + \exp(\beta*100)} + 10000 \frac{\exp(\beta *100)}{\exp(\beta *15) + \exp(\beta*30) + \exp(\beta*100)}}\\
R_{2} = 0.706\\

R_{3} = \frac{10000}{60000 \frac{\exp(\beta *100)}{\exp(\beta *15) + \exp(\beta*100) + \exp(\beta*100)} + 160000 \frac{\exp(\beta *15)}{\exp(\beta *15) + \exp(\beta*100) + \exp(\beta*100)} + 10000 \frac{\exp(\beta *15)}{\exp(\beta *15) + \exp(\beta*100) + \exp(\beta*100)}}\\
R_{3} = 0.995\\

\end{array}
\end{equation}

Step two:

\begin{equation}
\begin{array}{l}
A_{i} = {\sum_j R_{j}\frac{f(c_{ij})}{\sum_j f(c_{ij})}}

\\A_{A} = 1.278\frac{\exp(\beta*15)}{\exp(\beta *15) + \exp(\beta*30) + \exp(\beta*100)} + 0.706 \frac{\exp(\beta*30)}{(\exp(\beta *15) + \exp(\beta*30) + \exp(\beta*100))} + 0.995 \frac{\exp(\beta*100)}{(\exp(\beta *15) + \exp(\beta*30) + \exp(\beta*100))}\\

A_{B} = 1.278\frac{\exp(\beta*30)}{\exp(\beta *15) + \exp(\beta*30) + \exp(\beta*100)} + 0.706 \frac{\exp(\beta*15)}{(\exp(\beta *15) + \exp(\beta*30) + \exp(\beta*100))} + 0.995 \frac{\exp(\beta*100)}{(\exp(\beta *15) + \exp(\beta*30) + \exp(\beta*100))}\\

A_{C} = 1.278\frac{\exp(\beta*100)}{\exp(\beta *15) + \exp(\beta*100) + \exp(\beta*100)} + 0.706 \frac{\exp(\beta*100)}{(\exp(\beta *15) + \exp(\beta*100) + \exp(\beta*100))} + 0.995 \frac{\exp(\beta*15}{(\exp(\beta *15) + \exp(\beta*100) + \exp(\beta*100))}\\

A_{A} = 1.173 \\
A_{B} = 0.810 \\
A_{C} = 0.996 \\
\end{array}
\end{equation}

In the B2SFCA, the PPR \(R_{j}\) for each employment center can be
interpreted as the total number of jobs accessible to the total
population after being \emph{proportionally} adjusted to the travel
cost. The PPR \(R_{j}\) is then allocated, proportionally based on
travel cost, to each employment center. For this reason, the sum of all
\(A_{i}\) adds up to 2.98, the same value as the sum of all \(R_{j}\).

\hypertarget{inverse-balancing-accessibility-doubly-constrained}{%
\subsection{Inverse Balancing accessibility,
doubly-constrained}\label{inverse-balancing-accessibility-doubly-constrained}}

This measure results in a opportunities per person metric, however, it
constraints opportunities and population from both sides, estimating
accessibility iteratively. The formulation requires the number of
opportunities equals the population so they propose the iterative
estimates are standardized such that opportunities equals population and
the disbalanced is carried through as a factor. The formulation for the
synthetic example would take the following form:

\begin{equation}
\begin{array}{l}
A_{i} = \frac{\bar A^{o}}{\bar A^{c}}{\sum_{j=1}^{J} \frac{O_{j}f(c_{ij})}{L_{j}}}\\
L_{i} = {\sum_{i=1}^{I} \frac{P_{i}f(c_{ij})}{A_{i}}}\\
\end{array}
\end{equation}

Iteration 1:

\begin{equation}
\begin{array}{l}
A_{P1} = (1)*\frac{750\exp(\beta*2548.1) + 220*\exp(\beta *5419.1)}{1} = 16.47\\
A_{P2} = (1)*\frac{750\exp(\beta*1314.1) + 220*\exp(\beta *4762.6)}{1} = 104.65\\
A_{P3} = (1)*\frac{750\exp(\beta*2170.2) + 220*\exp(\beta *1790.1)}{1} = 43.93\\
L_{E1} = \frac{260\exp(\beta*2548.1)}{16.47} + \frac{255*\exp(\beta *1314.1)}{104.65} + \frac{495*\exp(\beta *2170.2)}{43.93} = 1.12\\
L_{E2} = \frac{260\exp(\beta*5419.1)}{16.47} + \frac{255*\exp(\beta *4762.6)}{104.65} + \frac{495*\exp(\beta *1790.1)}{43.93} = 0.78\\
\end{array}
\end{equation}

We can complete 8 more iterations until we reach convergence at the
second decimal level. I skip writing them out but the final \(A_{i}\)
values appear like:

\begin{equation}
\begin{array}{l}
A_{P1} = 14.56\\
A_{P2} = 92.35\\
A_{P3} = 47.05\\
\end{array}
\end{equation}

\newpage

\hypertarget{references}{%
\section*{References}\label{references}}
\addcontentsline{toc}{section}{References}

\hypertarget{refs}{}
\begin{CSLReferences}{1}{0}
\leavevmode\vadjust pre{\hypertarget{ref-allen2019}{}}%
Allen, J., Farber, S., 2019. A Measure of Competitive Access to
Destinations for Comparing Across Multiple Study Regions. Geographical
Analysis 52, 69--86.
doi:\href{https://doi.org/10.1111/gean.12188}{10.1111/gean.12188}

\leavevmode\vadjust pre{\hypertarget{ref-allen_suburbanization_2021}{}}%
Allen, J., Farber, S., 2021. Suburbanization of {Transport} {Poverty}.
Annals of the American Association of Geographers 111, 18.

\leavevmode\vadjust pre{\hypertarget{ref-Arranz2019measuring}{}}%
Arranz-López, A., Soria-Lara, J.A., Witlox, F., Páez, A., 2019.
Measuring relative non-motorized accessibility to retail activities.
International Journal of Sustainable Transportation 13, 639--651.
doi:\href{https://doi.org/10.1080/15568318.2018.1498563}{10.1080/15568318.2018.1498563}

\leavevmode\vadjust pre{\hypertarget{ref-arribas2021Open}{}}%
Arribas-Bel, D., Green, M., Rowe, F., Singleton, A., 2021. Open data
products-a framework for creating valuable analysis ready data. Journal
of Geographical Systems 23, 497--514.
doi:\href{https://doi.org/10.1007/s10109-021-00363-5}{10.1007/s10109-021-00363-5}

\leavevmode\vadjust pre{\hypertarget{ref-barboza_balancing_2021}{}}%
Barboza, M.H.C., Carneiro, M.S., Falavigna, C., Luz, G., Orrico, R.,
2021. Balancing time: {Using} a new accessibility measure in {Rio} de
{Janeiro}. Journal of Transport Geography 90, 102924.
doi:\href{https://doi.org/10.1016/j.jtrangeo.2020.102924}{10.1016/j.jtrangeo.2020.102924}

\leavevmode\vadjust pre{\hypertarget{ref-batista_estimation_2019}{}}%
Batista, S.F.A., Leclercq, L., Geroliminis, N., 2019. Estimation of
regional trip length distributions for the calibration of the aggregated
network traffic models. Transportation Research Part B: Methodological
122, 192--217.
doi:\href{https://doi.org/10.1016/j.trb.2019.02.009}{10.1016/j.trb.2019.02.009}

\leavevmode\vadjust pre{\hypertarget{ref-bocarejo_s_transport_2012}{}}%
Bocarejo S., J.P., Oviedo H., D.R., 2012. Transport accessibility and
social inequities: A tool for identification of mobility needs and
evaluation of transport investments. Journal of Transport Geography 24,
142--154.
doi:\href{https://doi.org/10.1016/j.jtrangeo.2011.12.004}{10.1016/j.jtrangeo.2011.12.004}

\leavevmode\vadjust pre{\hypertarget{ref-boisjoly2017informality}{}}%
Boisjoly, G., Moreno-Monroy, A.I., El-Geneidy, A., 2017. Informality and
accessibility to jobs by public transit: Evidence from the são paulo
metropolitan region. Journal of Transport Geography 64, 89--96.
doi:\href{https://doi.org/10.1016/j.jtrangeo.2017.08.005}{10.1016/j.jtrangeo.2017.08.005}

\leavevmode\vadjust pre{\hypertarget{ref-brunsdon2021opening}{}}%
Brunsdon, C., Comber, A., 2021. Opening practice: Supporting
reproducibility and critical spatial data science. Journal of
Geographical Systems 23, 477--496.
doi:\href{https://doi.org/10.1007/s10109-020-00334-2}{10.1007/s10109-020-00334-2}

\leavevmode\vadjust pre{\hypertarget{ref-cervero_transportation_2002}{}}%
Cervero, R., Sandoval, O., Landis, J., 2002. Transportation as a
{Stimulus} of {Welfare}-to-{Work}: {Private} versus {Public} {Mobility}.
Journal of Planning Education and Research 22, 50--63.
doi:\href{https://doi.org/10.1177/0739456X0202200105}{10.1177/0739456X0202200105}

\leavevmode\vadjust pre{\hypertarget{ref-chen_evaluating_2020}{}}%
Chen, B.Y., Cheng, X.-P., Kwan, M.-P., Schwanen, T., 2020. Evaluating
spatial accessibility to healthcare services under travel time
uncertainty: {A} reliability-based floating catchment area approach.
Journal of Transport Geography 87, 102794.
doi:\href{https://doi.org/10.1016/j.jtrangeo.2020.102794}{10.1016/j.jtrangeo.2020.102794}

\leavevmode\vadjust pre{\hypertarget{ref-chen_enhancing_2019}{}}%
Chen, X., 2019. Enhancing the {Two}-{Step} {Floating} {Catchment} {Area}
{Model} for {Community} {Food} {Access} {Mapping}: {Case} of the
{Supplemental} {Nutrition} {Assistance} {Program}. The Professional
Geographer 71, 668--680.
doi:\href{https://doi.org/10.1080/00330124.2019.1578978}{10.1080/00330124.2019.1578978}

\leavevmode\vadjust pre{\hypertarget{ref-chen_spatial_2020}{}}%
Chen, Z., Zhou, X., Yeh, A.G., 2020. Spatial accessibility to
kindergartens using a spectrum combinational approach: {Case} study of
{Shanghai} using cellphone data. Environment and Planning B: Urban
Analytics and City Science 239980832095422.
doi:\href{https://doi.org/10.1177/2399808320954221}{10.1177/2399808320954221}

\leavevmode\vadjust pre{\hypertarget{ref-data_management_group_tts_2018}{}}%
Data Management Group, 2018.
\href{http://dmg.utoronto.ca/transportation-tomorrow-survey/tts-introduction}{{TTS}
- {Transportation} {Tomorrow} {Survey} 2016}.

\leavevmode\vadjust pre{\hypertarget{ref-deboosere2018}{}}%
Deboosere, R., El-Geneidy, A.M., Levinson, D., 2018.
Accessibility-oriented development. Journal of Transport Geography 70,
11--20.
doi:\href{https://doi.org/10.1016/j.jtrangeo.2018.05.015}{10.1016/j.jtrangeo.2018.05.015}

\leavevmode\vadjust pre{\hypertarget{ref-fitdistrplus_2015}{}}%
Delignette-Muller, M.L., Dutang, C., 2015.
\href{https://www.jstatsoft.org/article/view/v064i04}{{fitdistrplus}: An
{R} package for fitting distributions}. Journal of Statistical Software
64, 1--34.

\leavevmode\vadjust pre{\hypertarget{ref-el-geneidy_mapping_2006}{}}%
El-Geneidy, A., Levinson, D., 2006. Mapping {Accessibility} {Over}
{Time}. Journal of Maps 12.

\leavevmode\vadjust pre{\hypertarget{ref-elgeneidy_cost_2016}{}}%
El-Geneidy, A., Levinson, D., Diab, E., Boisjoly, G., Verbich, D.,
Loong, C., 2016. The cost of equity: {Assessing} transit accessibility
and social disparity using total travel cost. Transportation Research
Part A: Policy and Practice 91, 302--316.
doi:\href{https://doi.org/10.1016/j.tra.2016.07.003}{10.1016/j.tra.2016.07.003}

\leavevmode\vadjust pre{\hypertarget{ref-geurs2004}{}}%
Geurs, K.T., van Wee, B., 2004. Accessibility evaluation of land-use and
transport strategies: review and research directions. Journal of
Transport Geography 12, 127--140.
doi:\href{https://doi.org/10.1016/j.jtrangeo.2003.10.005}{10.1016/j.jtrangeo.2003.10.005}

\leavevmode\vadjust pre{\hypertarget{ref-handy2020}{}}%
Handy, S., 2020. Is accessibility an idea whose time has finally come?
Transportation Research Part D: Transport and Environment 83, 102319.
doi:\href{https://doi.org/10.1016/j.trd.2020.102319}{10.1016/j.trd.2020.102319}

\leavevmode\vadjust pre{\hypertarget{ref-handy_measuring_1997}{}}%
Handy, S.L., Niemeier, D.A., 1997. Measuring {Accessibility}: {An}
{Exploration} of {Issues} and {Alternatives}. Environment and Planning
A: Economy and Space 29, 1175--1194.
doi:\href{https://doi.org/10.1068/a291175}{10.1068/a291175}

\leavevmode\vadjust pre{\hypertarget{ref-hansen1959}{}}%
Hansen, W.G., 1959. How Accessibility Shapes Land Use. Journal of the
American Institute of Planners 25, 73--76.
doi:\href{https://doi.org/10.1080/01944365908978307}{10.1080/01944365908978307}

\leavevmode\vadjust pre{\hypertarget{ref-harris_market_1954}{}}%
Harris, C.D., 1954. \href{https://www.jstor.org/stable/2561395}{The
{Market} as a {Factor} in the {Localization} of {Industry} in the
{United} {States}}. Annals of the Association of American Geographers
44, 315--348.

\leavevmode\vadjust pre{\hypertarget{ref-higgins2019}{}}%
Higgins, C.D., 2019. Accessibility toolbox for r and ArcGIS. Transport
Findings. doi:\href{https://doi.org/10.32866/8416}{10.32866/8416}

\leavevmode\vadjust pre{\hypertarget{ref-higgins2021changes}{}}%
Higgins, C.D., Páez, A., Ki, G., Wang, J., 2021. Changes in
accessibility to emergency and community food services during COVID-19
and implications for low income populations in hamilton, ontario. Social
Science \& Medicine 114442.
doi:\href{https://doi.org/10.1016/j.socscimed.2021.114442}{10.1016/j.socscimed.2021.114442}

\leavevmode\vadjust pre{\hypertarget{ref-horbachov_theoretical_2018}{}}%
Horbachov, P., Svichynskyi, S., 2018.
\href{https://www.jstor.org/stable/26622420}{Theoretical substantiation
of trip length distribution for home-based work trips in urban transit
systems}. Journal of Transport and Land Use 11, 593--632.

\leavevmode\vadjust pre{\hypertarget{ref-horner_exploring_2004}{}}%
Horner, M.W., 2004. Exploring {Metropolitan} {Accessibility} and {Urban}
{Structure}. Urban Geography 25, 264--284.
doi:\href{https://doi.org/10.2747/0272-3638.25.3.264}{10.2747/0272-3638.25.3.264}

\leavevmode\vadjust pre{\hypertarget{ref-joseph1984}{}}%
Joseph, A.E., Bantock, P.R., 1984. Rural Accessibility of General
Practitioners: the Case of Bruce and Grey Counties, ONTARIO,
1901{\textendash}1981. The Canadian Geographer/Le Géographe canadien 28,
226--239.
doi:\href{https://doi.org/10.1111/j.1541-0064.1984.tb00788.x}{10.1111/j.1541-0064.1984.tb00788.x}

\leavevmode\vadjust pre{\hypertarget{ref-kelobonye2020measuring}{}}%
Kelobonye, K., Zhou, H., McCarney, G., Xia, J., 2020. Measuring the
accessibility and spatial equity of urban services under competition
using the cumulative opportunities measure. Journal of Transport
Geography 85, 102706.
doi:\url{https://doi.org/10.1016/j.jtrangeo.2020.102706}

\leavevmode\vadjust pre{\hypertarget{ref-kwan_spacetime_1998}{}}%
Kwan, M.-P., 1998. Space-{Time} and {Integral} {Measures} of
{Individual} {Accessibility}: {A} {Comparative} {Analysis} {Using} a
{Point}-based {Framework}. Geographical Analysis 30, 191--216.
doi:\href{https://doi.org/10.1111/j.1538-4632.1998.tb00396.x}{10.1111/j.1538-4632.1998.tb00396.x}

\leavevmode\vadjust pre{\hypertarget{ref-levinson_accessibility_1998}{}}%
Levinson, D.M., 1998. Accessibility and the journey to work. Journal of
Transport Geography 6, 11--21.
doi:\href{https://doi.org/10.1016/S0966-6923(97)00036-7}{10.1016/S0966-6923(97)00036-7}

\leavevmode\vadjust pre{\hypertarget{ref-li_approach_2020}{}}%
Li, A., Huang, Y., Axhausen, K.W., 2020. An approach to imputing
destination activities for inclusion in measures of bicycle
accessibility. Journal of Transport Geography 82, 102566.
doi:\href{https://doi.org/10.1016/j.jtrangeo.2019.102566}{10.1016/j.jtrangeo.2019.102566}

\leavevmode\vadjust pre{\hypertarget{ref-luo2003}{}}%
Luo, W., Wang, F., 2003. Measures of Spatial Accessibility to Health
Care in a GIS Environment: Synthesis and a Case Study in the Chicago
Region. Environment and Planning B: Planning and Design 30, 865--884.
doi:\href{https://doi.org/10.1068/b29120}{10.1068/b29120}

\leavevmode\vadjust pre{\hypertarget{ref-merlin2017competition}{}}%
Merlin, L.A., Hu, L., 2017. Does competition matter in measures of job
accessibility? Explaining employment in los angeles. Journal of
Transport Geography 64, 77--88.
doi:\href{https://doi.org/10.1016/j.jtrangeo.2017.08.009}{10.1016/j.jtrangeo.2017.08.009}

\leavevmode\vadjust pre{\hypertarget{ref-miller2018}{}}%
Miller, E.J., 2018. Accessibility: measurement and application in
transportation planning. Transport Reviews 38, 551--555.
doi:\href{https://doi.org/10.1080/01441647.2018.1492778}{10.1080/01441647.2018.1492778}

\leavevmode\vadjust pre{\hypertarget{ref-paez2004network}{}}%
Paez, A., 2004. Network accessibility and the spatial distribution of
economic activity in eastern asia. Urban Studies 41, 2211--2230.

\leavevmode\vadjust pre{\hypertarget{ref-paez2019}{}}%
Paez, A., Higgins, C.D., Vivona, S.F., 2019. Demand and level of service
inflation in Floating Catchment Area (FCA) methods. PLOS ONE 14,
e0218773.
doi:\href{https://doi.org/10.1371/journal.pone.0218773}{10.1371/journal.pone.0218773}

\leavevmode\vadjust pre{\hypertarget{ref-paez2012measuring}{}}%
Paez, A., Scott, D.M., Morency, C., 2012. Measuring accessibility:
Positive and normative implementations of various accessibility
indicators. Journal of Transport Geography 25, 141--153.
doi:\href{https://doi.org/10.1016/j.jtrangeo.2012.03.016}{10.1016/j.jtrangeo.2012.03.016}

\leavevmode\vadjust pre{\hypertarget{ref-paez2021open}{}}%
Páez, A., 2021. Open spatial sciences: An introduction. Journal of
Geographical Systems 23, 467--476.
doi:\href{https://doi.org/10.1007/s10109-021-00364-4}{10.1007/s10109-021-00364-4}

\leavevmode\vadjust pre{\hypertarget{ref-pereira_distributional_2019}{}}%
Pereira, R.H.M., Banister, D., Schwanen, T., Wessel, N., 2019.
Distributional effects of transport policies on inequalities in access
to opportunities in {Rio} de {Janeiro}. Journal of Transport and Land
Use 12.
doi:\href{https://doi.org/10.5198/jtlu.2019.1523}{10.5198/jtlu.2019.1523}

\leavevmode\vadjust pre{\hypertarget{ref-proffitt2017}{}}%
Proffitt, D.G., Bartholomew, K., Ewing, R., Miller, H.J., 2017.
Accessibility planning in American metropolitan areas: Are we there yet?
Urban Studies 56, 167--192.
doi:\href{https://doi.org/10.1177/0042098017710122}{10.1177/0042098017710122}

\leavevmode\vadjust pre{\hypertarget{ref-qi_decadelong_2018}{}}%
Qi, Y., Fan, Y., Sun, T., Hu, L.(Ivy)., 2018. Decade-long changes in
spatial mismatch in {Beijing}, {China}: {Are} disadvantaged populations
better or worse off? Environment and Planning A: Economy and Space 50,
848--868.
doi:\href{https://doi.org/10.1177/0308518X18755747}{10.1177/0308518X18755747}

\leavevmode\vadjust pre{\hypertarget{ref-r5r_2021}{}}%
Rafael H. M. Pereira, Marcus Saraiva, Daniel Herszenhut, Carlos Kaue
Vieira Braga, Matthew Wigginton Conway, 2021. r5r: Rapid realistic
routing on multimodal transport networks with R5 in r. Findings.
doi:\href{https://doi.org/10.32866/001c.21262}{10.32866/001c.21262}

\leavevmode\vadjust pre{\hypertarget{ref-reggiani_accessibility_2011}{}}%
Reggiani, A., Bucci, P., Russo, G., 2011. Accessibility and {Impedance}
{Forms}: {Empirical} {Applications} to the {German} {Commuting}
{Network}. International Regional Science Review 34, 230--252.
doi:\href{https://doi.org/10.1177/0160017610387296}{10.1177/0160017610387296}

\leavevmode\vadjust pre{\hypertarget{ref-rosik_forecast_2021}{}}%
Rosik, P., Goliszek, S., Komornicki, T., Duma, P., 2021. Forecast of the
{Impact} of {Electric} {Car} {Battery} {Performance} and
{Infrastructural} and {Demographic} {Changes} on {Cumulative}
{Accessibility} for the {Five} {Most} {Populous} {Cities} in {Poland}.
Energies 14, 8350.
doi:\href{https://doi.org/10.3390/en14248350}{10.3390/en14248350}

\leavevmode\vadjust pre{\hypertarget{ref-santanapalacios2022}{}}%
Santana Palacios, M., El-geneidy, A., 2022. Cumulative versus
Gravity-based Accessibility Measures: Which One to Use? Findings.
doi:\href{https://doi.org/10.32866/001c.32444}{10.32866/001c.32444}

\leavevmode\vadjust pre{\hypertarget{ref-shen1998}{}}%
Shen, Q., 1998. Location characteristics of inner-city neighborhoods and
employment accessibility of low-wage workers. Environment and Planning
B: Planning and Design 25, 345--365.
doi:\href{https://doi.org/10.1068/b250345}{10.1068/b250345}

\leavevmode\vadjust pre{\hypertarget{ref-shi_literature_2020}{}}%
Shi, Y., Blainey, S., Sun, C., Jing, P., 2020. A literature review on
accessibility using bibliometric analysis techniques. Journal of
Transport Geography 87, 102810.
doi:\href{https://doi.org/10.1016/j.jtrangeo.2020.102810}{10.1016/j.jtrangeo.2020.102810}

\leavevmode\vadjust pre{\hypertarget{ref-siddiq_tools_2021}{}}%
Siddiq, F., D. Taylor, B., 2021. Tools of the {Trade}?: {Assessing} the
{Progress} of {Accessibility} {Measures} for {Planning} {Practice}.
Journal of the American Planning Association 87, 497--511.
doi:\href{https://doi.org/10.1080/01944363.2021.1899036}{10.1080/01944363.2021.1899036}

\leavevmode\vadjust pre{\hypertarget{ref-vale_influence_2017}{}}%
Vale, D.S., Pereira, M., 2017. The influence of the impedance function
on gravity-based pedestrian accessibility measures: {A} comparative
analysis. Environment and Planning B: Urban Analytics and City Science
44, 740--763.
doi:\href{https://doi.org/10.1177/0265813516641685}{10.1177/0265813516641685}

\leavevmode\vadjust pre{\hypertarget{ref-vickerman_accessibility_1974}{}}%
Vickerman, R.W., 1974. Accessibility, {Attraction}, and {Potential}: {A}
{Review} of {Some} {Concepts} and {Their} {Use} in {Determining}
{Mobility}. Environment and Planning A: Economy and Space 6, 675--691.
doi:\href{https://doi.org/10.1068/a060675}{10.1068/a060675}

\leavevmode\vadjust pre{\hypertarget{ref-wachs_physical_1973}{}}%
Wachs, M., Kumagai, T.G., 1973. Physical accessibility as a social
indicator. Socio-Economic Planning Sciences 7, 437--456.
doi:\href{https://doi.org/10.1016/0038-0121(73)90041-4}{10.1016/0038-0121(73)90041-4}

\leavevmode\vadjust pre{\hypertarget{ref-wang_access_2021}{}}%
Wang, S., Wang, M., Liu, Y., 2021. Access to urban parks: {Comparing}
spatial accessibility measures using three {GIS}-based approaches.
Computers, Environment and Urban Systems 90, 101713.
doi:\href{https://doi.org/10.1016/j.compenvurbsys.2021.101713}{10.1016/j.compenvurbsys.2021.101713}

\leavevmode\vadjust pre{\hypertarget{ref-weibull_axiomatic_1976}{}}%
Weibull, J.W., 1976. An axiomatic approach to the measurement of
accessibility. Regional Science and Urban Economics 6, 357--379.
doi:\href{https://doi.org/10.1016/0166-0462(76)90031-4}{10.1016/0166-0462(76)90031-4}

\leavevmode\vadjust pre{\hypertarget{ref-wilson1971}{}}%
Wilson, A.G., 1971. A Family of Spatial Interaction Models, and
Associated Developments. Environment and Planning A: Economy and Space
3, 1--32. doi:\href{https://doi.org/10.1068/a030001}{10.1068/a030001}

\leavevmode\vadjust pre{\hypertarget{ref-yan2021}{}}%
Yan, X., 2021. Toward Accessibility-Based Planning. Journal of the
American Planning Association 87, 409--423.
doi:\href{https://doi.org/10.1080/01944363.2020.1850321}{10.1080/01944363.2020.1850321}

\leavevmode\vadjust pre{\hypertarget{ref-yang_comparing_2006}{}}%
Yang, D.-H., Goerge, R., Mullner, R., 2006. Comparing {GIS}-{Based}
{Methods} of {Measuring} {Spatial} {Accessibility} to {Health}
{Services}. Journal of Medical Systems 30, 23--32.
doi:\href{https://doi.org/10.1007/s10916-006-7400-5}{10.1007/s10916-006-7400-5}

\leavevmode\vadjust pre{\hypertarget{ref-ye_spatial_2018}{}}%
Ye, C., Zhu, Y., Yang, J., Fu, Q., 2018. Spatial equity in accessing
secondary education: {Evidence} from a gravity-based model: {Spatial}
equity in accessing secondary education. The Canadian Geographer / Le
Géographe canadien 62, 452--469.
doi:\href{https://doi.org/10.1111/cag.12482}{10.1111/cag.12482}

\end{CSLReferences}


\end{document}
